# Jekyll Site Configuration

title: Convergence Examples
email: webmaster@econvergence.io
description: >-
  Convergence is a next generation API that allows developers to build rich, real-time collaboration into their applications.

url: "https://examples.convergence.io/"
host: 0.0.0.0

# Build settings
source: src
markdown: kramdown
plugins:
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - README.md
  - Dockerfile
  - Jenkinsfile
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

keep_files: 
  - libs